### PR TITLE
Tests: Add example for StringListParamType interference when running cli multiple times

### PR DESCRIPTION
**Pull request by gutzbenj**
Dear all, dear @lewoudar ,

this PR is meant to show some issue that we ran into within our test suite for wetterdienst at [1]. It accompanies
the issue #22 . The second assert would currently fail.

Sincerely,
Benjamin

/CC @amotl

[1] https://github.com/earthobservations/wetterdienst

### CODE REVIEW

**Comment by lewoudar** [comment]
Ok, seems like Windows CI is not working, I'm sure of the issue, can you try to update dependencies to see if it works better?

**Comment by lewoudar** [comment]
Also, I just saw it now, can you remove the private attribute `self._convert_called` and the places where it is used in tests please

**Comment by gutzbenj** [comment]
Done!

**Comment by lewoudar** [comment]
Thanks for the work @gutzbenj 
I will probably update some dependencies before releasing a new version this week :)

**Pull request merged**
